### ISSUE TITLE
Example of Pressure-Deflection Diagram

### ISSUE THREAD

**Issue by Royppp** [Davide-sd/pygasflow#4]
The example of Pressure-Deflection Diagram in the official website(https://pygasflow.readthedocs.io/en/latest/examples/tut-6.html) maybe wrong about dealing with the relation between pressure ratio 1 and pressure ratio 2:
  To get the pressure ratio of Mach 2 curve, in aerodynamics,pr_1[idx] and pr_2 maybe should be multiplied together instead of add them together and minus 1?

**Comment by Davide-sd** [comment]
Hello @Royppp ,

sorry for this very late reply. You raise a very good question, which can be rephrased as: _what is shown on a pressure-deflection diagram?_ The obvious answer would be pressure and deflection. However...

...This example was built by following the procedure written in section _"4.8 Pressure-Deflection Diagrams"_ of _"Modern Compressible Flow, J.D. Anderson"_. In particular, I tried to come up with what was shown in Figure 4.22, which on the vertical axis shows the static pressure. But I think that's a typing error: if it really was the static pressure, then the maximum pressure for Mach 2 curve would be higher than the maximum pressure for Mach 1 curve. This situation, however, is not depicted on the plot.

So, I built the plot using the pressure ratio on the vertical axis. Each curve uses the pressure ratio associated to a particular shock wave, without considering previous (upstream) shockwaves. This leads to one interesting aspect of the pressure-deflection diagrams: the biggest curve (in the vertical direction) is the one associate to the first shockwave, with the other one being smaller. Hence, the overall plot is more compact and easier to read. On the other hand, if we were to consider the pressure ratios of upstream shockwaves, each new curve would be bigger (in the vertical axis) than the previous one, which would make the plot more difficult to read.

This, I believe, is a feature of the pressure-deflection diagram which was not stated in the aforementioned section of that book. Note that I self-studied this particular argument, without having the privilege of interacting with any professor. If you are a student at some university, you might want to ask this question to your professor...

**Comment by Davide-sd** [comment]
@Royppp, you are correct: I did everything wrong in that example :)

I had the time to dig into pressure-deflection diagrams, understand all the steps involved into their creation, so I implemented a new and much easier way to create this kind of diagrams, which should significantly reduce the risk of doing something wrong. The example you linked can now be easily created with:

```py
# Known data
gamma = 1.4
M1 = 2.8
theta1 = 16

l1 = PressureDeflectionLocus(M=M1, gamma=gamma, label="1")
l2 = l1.new_locus_from_shockwave(theta1, label="2")

d = PressureDeflectionDiagram()
d.add_locus(l1)
d.add_locus(l2)
l, arrows = d.add_path((l1, theta1), (l2, 0))
d.add_state(0, l2.func_of_theta(0)[0], "3")
d.move_legend_outside()
d.y_range = (0, 14)
d
```
![image](https://github.com/user-attachments/assets/d65565b2-eca8-45a1-ac6d-aa1147109b56)

The code still needs some polishing before creating a new release, which I expect it to be during Christmas holiday... maybe sooner. In the meantime, I'll leave this issue open.

Thank you very much for letting me know about this issue.

**Comment by Royppp** [comment]
Thank you for your response! I am very much looking forward to the new feature you mentioned. Your pygasflow is fantastic—it has greatly simplified my research and studies during graduate school. I will be including you and your code in the acknowledgments section of my thesis.

**Comment by Royppp** [comment]
@Davide-sd Thank you for your response! I am very much looking forward to the new feature you mentioned. Your pygasflow is fantastic—it has greatly simplified my research and studies during graduate school. I will be including you and your code in the acknowledgments section of my thesis.

**Comment by Davide-sd** [comment]
Thanks for the kind words :)

I just released a new version of this module on PyPi. It should be available through conda in a couple of days. Here are a few links to the documentation:

* [`PressureDeflectionLocus`](https://pygasflow.readthedocs.io/en/latest/modules/shockwave.html#pygasflow.shockwave.PressureDeflectionLocus).
* [`PressureDeflectionDiagram`](https://pygasflow.readthedocs.io/en/latest/modules/interactive.html#pygasflow.interactive.diagrams.PressureDeflectionDiagram).
* [Tutorials](https://pygasflow.readthedocs.io/en/latest/examples/tut-0.html) on using `PressureDeflectionLocus` and `PressureDeflectionDiagrams`.

I'm closing this issue. Feel free to open a new issue if you think the documentation needs improvements, or you find bugs, or to suggest new features.
